// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyx7SKAWqoTTwsjI_-rIinp23x99QGw6s',
    appId: '1:328435745541:web:e6c78d75c1ce799fa52d6c',
    messagingSenderId: '328435745541',
    projectId: 'dogmbti-d7fa7',
    authDomain: 'dogmbti-d7fa7.firebaseapp.com',
    storageBucket: 'dogmbti-d7fa7.appspot.com',
    measurementId: 'G-2VJMFSB6TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FvNFxolHFV3Y2YQIrrQvyBs8fneHwhY',
    appId: '1:328435745541:android:6c8e20490e7b9c08a52d6c',
    messagingSenderId: '328435745541',
    projectId: 'dogmbti-d7fa7',
    storageBucket: 'dogmbti-d7fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzn8rgJdvNG6le22sQGqyWuPzJpaVE0bc',
    appId: '1:328435745541:ios:332d0eec51aed4d9a52d6c',
    messagingSenderId: '328435745541',
    projectId: 'dogmbti-d7fa7',
    storageBucket: 'dogmbti-d7fa7.appspot.com',
    iosClientId:
        '328435745541-4ao48u2pkjnggt28pbv7hicisjjjc1qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogmbti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzn8rgJdvNG6le22sQGqyWuPzJpaVE0bc',
    appId: '1:328435745541:ios:332d0eec51aed4d9a52d6c',
    messagingSenderId: '328435745541',
    projectId: 'dogmbti-d7fa7',
    storageBucket: 'dogmbti-d7fa7.appspot.com',
    iosClientId:
        '328435745541-4ao48u2pkjnggt28pbv7hicisjjjc1qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogmbti',
  );
}
